In [1]:
import numpy as np
# log_mentah berisi data string yang perlu dibersihkan
log_mentah = [
    "   NANDA, 1500, 200, 60   ",
    "CHANGLI, 2200, 150, 90",
    "   MAISIE, 1800, 300, 75   ",
    "   VEDAL, 3000, 100, 120 ",
    "NEURO-SAMA, 1200, 400, 80"
]
# Format data: NAMA, DAMAGE_DEALT, DAMAGE_TAKEN, DURATION_SECONDS

In [26]:
def proses_log(data_mentah):
    wadah_data_numerik = []
    for item in data_mentah:
        data_bersih_1 = item.strip()
        data_bersih_2 = item.split(',')
        angka_dalam_list = data_bersih_2[1:]
        data_bersih = []
        for str_number in angka_dalam_list:
            numerik_str = str_number.strip()
            numerik = int(numerik_str)
            data_bersih.append(numerik)
        wadah_data_numerik.append(data_bersih)
    array_numerik = np.array(wadah_data_numerik)
    return array_numerik
log_proses = proses_log(log_mentah)
print(log_proses)

[[1500  200   60]
 [2200  150   90]
 [1800  300   75]
 [3000  100  120]
 [1200  400   80]]


In [32]:
kolom_damage = log_proses[:, 0] #Sama seperti logika (baris, kolom)
print(f"Semua data damage: {kolom_damage}")

total_damage = kolom_damage.sum()
rata_rata_damage = kolom_damage.mean()
print(f"Total damage dari semua pertarungan: {total_damage}")
print(f"Rata-rata damage per pertarungan: {rata_rata_damage: .2f}")

damage_tertinggi = kolom_damage.max()
damage_terendah = kolom_damage.min()
print(f"Damage tertinggi yang tercatat: {damage_tertinggi}")
print(f"Damage terendah yang tercatat: {damage_terendah}")

Semua data damage: [1500 2200 1800 3000 1200]
Total damage dari semua pertarungan: 9700
Rata-rata damage per pertarungan:  1940.00
Damage tertinggi yang tercatat: 3000
Damage terendah yang tercatat: 1200


In [34]:
kolom_durasi = log_proses[:, 2]
print(f"Semua data durasi: {kolom_durasi}")

total_durasi = kolom_durasi.sum()
rerata_durasi = kolom_durasi.mean()
print(f"Total durasi dari semua pertarungan: {total_durasi}")
print(f"Rerata durasi per oertarungan: {rerata_durasi}")

durasi_terlama = kolom_durasi.max()
durasi_tersingkat = kolom_durasi.min()
print(f"Durasi terlama yang tercatat: {durasi_terlama}")
print(f"Durasi tersingkat yang tercatat: {durasi_tersingkat}")

Semua data durasi: [ 60  90  75 120  80]
Total durasi dari semua pertarungan: 425
Rerata durasi per oertarungan: 85.0
Durasi terlama yang tercatat: 120
Durasi tersingkat yang tercatat: 60


In [42]:
print("Matriks data kita:")
print(log_proses)
print("\n" + "="*50 + "\n")

total_per_kolom = log_proses.sum(axis=0)
print(f"Hasil dari .sum(axis=0): {total_per_kolom}")
print("Artinya: [Total Damage Dealt, Total Damage Taken, Total Duration]")
print(f"Contoh: Total Damage Dealt adalah {total_per_kolom[0]}")

print("\n" + "="*50 + "\n")

total_per_baris = log_proses.sum(axis=1)
print(f"Hasil dari .sum(axis=1): {total_per_baris}")
print("Artinya: [Total skor NANDA, Total skor CHANGLI, Total skor MAISIE, dst.]")
print(f"Contoh: Total skor untuk pertarungan pertama (NANDA) adalah {total_per_baris[0]}")

Matriks data kita:
[[1500  200   60]
 [2200  150   90]
 [1800  300   75]
 [3000  100  120]
 [1200  400   80]]


Hasil dari .sum(axis=0): [9700 1150  425]
Artinya: [Total Damage Dealt, Total Damage Taken, Total Duration]
Contoh: Total Damage Dealt adalah 9700


Hasil dari .sum(axis=1): [1760 2440 2175 3220 1680]
Artinya: [Total skor NANDA, Total skor CHANGLI, Total skor MAISIE, dst.]
Contoh: Total skor untuk pertarungan pertama (NANDA) adalah 1760
