In [26]:
import numpy as np

# Inventaris 4 pemain.
# Baris = Pemain (Nanda, Changli, Maisie, Vedal)
# Kolom = Sumber Daya (Kayu, Batu, Emas)
inventaris_pemain = np.array([
    [500, 300, 10],  # Nanda
    [200, 800, 50],  # Changli
    [100, 150, 150], # Maisie
    [400, 400, 20]   # Neuro-sama
])

# Harga setiap sumber daya di pasar
# Vektor 1D: [Harga Kayu, Harga Batu, Harga Emas]
harga_sumber_daya = np.array([5, 10, 100]) #Ini vektor, jadi tidak bisa di transpose

# Jumlah sumber daya yang diproduksi setiap pemain per jam
produksi_per_jam = np.array([
    [20, 15, 1], # Nanda
    [10, 30, 2], # Changli
    [5, 5, 10],  # Maisie
    [15, 15, 2]  # Vedal
])

# Bonus efisiensi unik untuk setiap pemain (diterapkan per jam)
# Ini adalah vektor kolom (bentuk 4x1)
bonus_efisiensi_pemain = np.array([[5], [10], [15], [5]])

In [33]:
#Menghitung kekayaan pemain
harga_sumber_daya_3x1 = harga_sumber_daya.reshape(3, 1)
kekayaan_pemain = inventaris_pemain @ harga_sumber_daya_3x1

#Menghitung produksi per 8 jam
total_produksi_per_jam = produksi_per_jam + bonus_efisiensi_pemain
total_produksi_per_8_jam = total_produksi_per_jam * 8

#Menghitung inventaris baru
inventaris_baru = inventaris_pemain + total_produksi_per_8_jam

#Laporan Akhir
laporan_final = np.hstack((inventaris_baru, kekayaan_pemain))

In [32]:
#Hasil akhir
print("\n" + "="*50)
print("\n--- KEKAYAAN PEMAIN ---")
print("\n", kekayaan_pemain)
print("\n" + "="*50)
print("\n--- INVENTARIS BARU ---")
print("[Jumlah Kayu] [Jumlah Batu] [Jumlah Emas]")
print("\n", inventaris_baru)
print("\n" + "="*50)
print("\n--- LAPORAN FINAL ---")
print("[Jumlah Kayu] [Jumlah Batu] [Jumlah Emas] [Kekayaan Pemain]")
print("\n", laporan_final)
print("\n" + "="*50)



--- KEKAYAAN PEMAIN ---

 [[ 6500]
 [14000]
 [17000]
 [ 8000]]


--- INVENTARIS BARU ---
[Jumlah Kayu] [Jumlah Batu] [Jumlah Emas]

 [[ 700  460   58]
 [ 360 1120  146]
 [ 260  310  350]
 [ 560  560   76]]


--- LAPORAN FINAL ---
[Jumlah Kayu] [Jumlah Batu] [Jumlah Emas] [Kekayaan Pemain]

 [[  700   460    58  6500]
 [  360  1120   146 14000]
 [  260   310   350 17000]
 [  560   560    76  8000]]

