In [2]:
import numpy as np

In [3]:
A = np.array([
    [1, 2, 3, 4],
    [4, 5, 6, 7]
])
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12],
    [14, 15]
])

print("--- Matriks A (bentuk 2x3) ---")
print(A)
print("Bentuk A:", A.shape)
print("\n--- Matriks B (bentuk 3x2) ---")
print(B)
print("Bentuk B:", B.shape)

print("\n" + "="*50 + "\n")
print("Mencoba perkalian element-wise (A * B)...")

try:
    hasil_kali_elementwise = A * B
    print(hasil_kali_elementwise)
except ValueError as e:
    print(f"ERROR: {e}")
    print("-> Gagal Karena perkalian element-wise (*) mengharuskan kedua matriks punya bentuk yang SAMA PERSIS.")

print("\n" + "="*50 + "\n")
print("Mencoba perkalian matriks (A * B)...")

hasil_dot_product = A @ B

print("Hasil A @ B:\n", hasil_dot_product)
print("Bentuk hasilnya:", hasil_dot_product.shape)
print("-> Berhasil! Bentuk hasilnya adalah (baris A,  kolom B) -> (2, 2).")

--- Matriks A (bentuk 2x3) ---
[[1 2 3 4]
 [4 5 6 7]]
Bentuk A: (2, 4)

--- Matriks B (bentuk 3x2) ---
[[ 7  8]
 [ 9 10]
 [11 12]
 [14 15]]
Bentuk B: (4, 2)


Mencoba perkalian element-wise (A * B)...
ERROR: operands could not be broadcast together with shapes (2,4) (4,2) 
-> Gagal Karena perkalian element-wise (*) mengharuskan kedua matriks punya bentuk yang SAMA PERSIS.


Mencoba perkalian matriks (A * B)...
Hasil A @ B:
 [[114 124]
 [237 259]]
Bentuk hasilnya: (2, 2)
-> Berhasil! Bentuk hasilnya adalah (baris A,  kolom B) -> (2, 2).
