In [1]:
import numpy as np

In [3]:
# Dataset nilai mahasiswa (6 mahasiswa, 4 mata kuliah)
np.random.seed(20)  # supaya konsisten
nilai = np.random.randint(60, 101, size=(6, 4))
print("--- Nilai Mahasiswa [MK01, MK02, MK03, MK04] ---\n")
print(nilai)

--- Nilai Mahasiswa [MK01, MK02, MK03, MK04] ---

[[ 95  86  75  91]
 [ 88  86  69  80]
 [ 71  82  67  94]
 [ 92 100  81  86]
 [ 86  79  76  98]
 [ 98  76  97  67]]


In [14]:
nilai_total_per_mahasiswa = nilai.sum(axis=1).reshape(6, 1)
nilai_rerata_per_mahasiswa = nilai_total_per_mahasiswa / 4
nilai_rerata_per_matkul = nilai.sum(axis=0).reshape(4, 1) / 6
print("\n", nilai_total_per_mahasiswa)
print("\n", nilai_rerata_per_mahasiswa)
print("\n", nilai_rerata_per_matkul)


 [[347]
 [323]
 [314]
 [359]
 [339]
 [338]]

 [[86.75]
 [80.75]
 [78.5 ]
 [89.75]
 [84.75]
 [84.5 ]]

 [[88.33333333]
 [84.83333333]
 [77.5       ]
 [86.        ]]


In [22]:
nilai_min = nilai.min(axis=0)
nilai_max = nilai.max(axis=0)
rentang_0_ke_1 = (nilai - nilai_min) / (nilai_max - nilai_min)
nilai_normal = np.round(rentang_0_ke_1, 1)
print(nilai_normal)

[[0.9 0.4 0.3 0.8]
 [0.6 0.4 0.1 0.4]
 [0.  0.2 0.  0.9]
 [0.8 1.  0.5 0.6]
 [0.6 0.1 0.3 1. ]
 [1.  0.  1.  0. ]]


In [26]:
bobot = [0.3, 0.2, 0.3, 0.2]
skor_akhir = nilai @ bobot
print(skor_akhir.reshape(6, 1))

[[86.4]
 [80.3]
 [76.6]
 [89.1]
 [84. ]
 [87.1]]


In [56]:
#Reshape: Aturannya adalah hasil kali baris dan kolom sama dengan matriks aslinya
skor_2x3 = skor_akhir.reshape(2, 3)
print(skor_2x3, "\n")
#Stacking: Aturannya adalah untuk .vstack jumlah kolom harus sama
#sedangkan .hstack berarti jumlah baris harus sama
id_mahasiswa = np.array([1, 2, 3, 4, 5, 6])
id_dengan_nilai = np.vstack([id_mahasiswa, skor_akhir])
print(id_dengan_nilai.T, "\n")
#Slicing
tiga_mahasiswa_pertama = skor_akhir.reshape(6, 1)[[0, 1, 2], :]
print(tiga_mahasiswa_pertama, "\n")
skor_diatas_85 = skor_akhir > 85
print(id_mahasiswa[skor_akhir > 85])

[[86.4 80.3 76.6]
 [89.1 84.  87.1]] 

[[ 1.  86.4]
 [ 2.  80.3]
 [ 3.  76.6]
 [ 4.  89.1]
 [ 5.  84. ]
 [ 6.  87.1]] 

[[86.4]
 [80.3]
 [76.6]] 

[1 4 6]
