In [2]:
import numpy as np

In [3]:
# Membuat matriks 5 baris, 4 kolom berisi angka 0 sampai 19
data = np.arange(20).reshape(5, 4)

print("--- Matriks Spesimen (5x4) ---")
print(data)

--- Matriks Spesimen (5x4) ---
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [6]:
print("--- Hasil Slicing ---")
elemen = data[1, 2] #Ingat bahwa indeks baris dan kolom dimulai dari 0
print(f"\nA. Satu elemen di [1, 2]: {elemen}\n")
baris_ketiga = data[3] #Bisa juga [3, :]
print(f"B. Baris ke-4 (indeks 3): {baris_ketiga}\n")
kolom_pertama = data[:, 0]
print(f"C. Kolom ke-1 (indeks 0):\n{kolom_pertama}\n")
pojok_kanan_bawah = data[3:, 2:] #Isinya akan 14, 15, 18, 19 di sebuah matriks 2x2
print(f"D. Potongan 2x2 di pojok kanan bawah:\n{pojok_kanan_bawah}\n")
bagian_tengah = data[1:4, 1:3] #: artinya sampai sebelum, mirip pada list kemarin
print(f"E. Potongan tengah (3x2):\n{bagian_tengah}")

--- Hasil Slicing ---

A. Satu elemen di [1, 2]: 6

B. Baris ke-4 (indeks 3): [12 13 14 15]

C. Kolom ke-1 (indeks 0):
[ 0  4  8 12 16]

D. Potongan 2x2 di pojok kanan bawah:
[[14 15]
 [18 19]]

E. Potongan tengah (3x2):
[[ 5  6]
 [ 9 10]
 [13 14]]


In [8]:
masker = data > 10

print("--- Matriks Asli ---")
print(data)
print(f"Shape: {data.shape}")
print("\n---  Masker Boolean (hasil dari kondisi 'data > 10') ---")
print(masker)
print(f"Shape: {masker.shape}")

--- Matriks Asli ---
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Shape: (5, 4)

---  Masker Boolean (hasil dari kondisi 'data > 10') ---
[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]
Shape: (5, 4)


In [9]:
hasil_filter = data[masker]
#Ini kurasa adalah slicing, hanya kita menggunakan var instead of indeks
print("--- Hasil Filter (hanya elemen yang 'True' di masker) ---")
print(hasil_filter)
print(f"Shape: {hasil_filter.shape}")
print("\n--- Hasil dalam satu baris ---")
print(data[data > 10]) #Tolong jelaskan sintaks ini lebih mendalam

--- Hasil Filter (hanya elemen yang 'True' di masker) ---
[11 12 13 14 15 16 17 18 19]
Shape: (9,)

--- Hasil dalam satu baris ---
[11 12 13 14 15 16 17 18 19]


In [14]:
print("--- Matriks Asli ---")
print(data)
baris_pilihan = data[[0, 2, 4]]
print("\n---- A. Baris Pilihan (indeks 0, 2, dan 4) ---")
print(baris_pilihan)
print(f"Shape: (Karena berbentuk list jadi tidak bisa digunakan .shape)")
kolom_pilihan = data[:, [0, 3]] #Semua baris, kolom 1 dan 4
print("\n--- B. Kolom Pilihan (indeks 0, 3) ---")
print(kolom_pilihan)
print(f"Shape: {kolom_pilihan.shape}")
elemen_pilihan = data[[0, 2, 4], [1, 2, 3]] #Akan mengambil nilai 5, 10, dan 19
print("\n--- C. Elemen Pilihan di [0, 1], [2, 2], dan [4, 3] ---")
print(elemen_pilihan)

--- Matriks Asli ---
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

---- A. Baris Pilihan (indeks 0, 2, dan 4) ---
[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]
Shape: (Karena berbentuk list jadi tidak bisa digunakan .shape)

--- B. Kolom Pilihan (indeks 0, 3) ---
[[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]
 [16 19]]
Shape: (5, 2)

--- C. Elemen Pilihan di [0, 1], [2, 2], dan [4, 3] ---
[ 1 10 19]


In [19]:
# Dataset 10 pertarungan, 5 metrik
# Metrik: [damage_dealt, damage_taken, healing_done, assists, duration]
data_harian = np.random.randint(low=1000, high=5000, size=(10, 5))

print("--- Dataset Awal (10x5) ---")
print("\n", data_harian)

--- Dataset Awal (10x5) ---

 [[1832 4676 1511 4012 4996]
 [4198 3885 2573 2816 4380]
 [1018 2741 2932 3666 3703]
 [1517 2957 3945 1221 4545]
 [1835 4144 1656 2589 4508]
 [2006 1672 2369 4115 1122]
 [3890 4781 4301 1979 2772]
 [2086 2474 2192 4710 1575]
 [4992 1621 2797 1538 1971]
 [3196 2704 4596 4323 1285]]


In [35]:
pemain_elite = data_harian[:, 0] > 3500
print(pemain_elite)
daftar_pemain_elite = data_harian[pemain_elite]
print("\n", daftar_pemain_elite)
metrik_penting = data_harian[pemain_elite][:, [1, 4]]
print("\n", metrik_penting)
laporan_final = metrik_penting[0]
print("\n", laporan_final)

[False  True False False False False  True False  True False]

 [[4198 3885 2573 2816 4380]
 [3890 4781 4301 1979 2772]
 [4992 1621 2797 1538 1971]]

 [[3885 4380]
 [4781 2772]
 [1621 1971]]

 [3885 4380]


In [32]:
print("--- Filter Pemain Elite ---")
print(pemain_elite)
print("\n--- Daftar Pemain Elite ---")
print(daftar_pemain_elite)
print("\n--- Metrik Penting ---")
print(metrik_penting)
print("\nL--- Laporan Final ---")
print(laporan_final)

--- Filter Pemain Elite ---
[False  True False False False False  True False  True False]

--- Daftar Pemain Elite ---
[[4198 3885 2573 2816 4380]
 [3890 4781 4301 1979 2772]
 [4992 1621 2797 1538 1971]]

--- Metrik Penting ---
[[3885 4380]
 [4781 2772]
 [1621 1971]]

L--- Laporan Final ---
[3885 4380]
