In [1]:
import numpy as np

In [2]:
vektor_panjang = np.arange(12)
print("--- Array Asli (1D, 2D elemen) ---")
print(vektor_panjang)
print("Bentuk asli:", vektor_panjang.shape)
print("Ukuran asli:", vektor_panjang.size)

matriks_3x4 = vektor_panjang.reshape(3, 4)
print("\n--- Reshape menjadi (3, 4) ---")
print(matriks_3x4)
print("Bentuk baru:", matriks_3x4.shape)

matriks_4x3 = vektor_panjang.reshape(4, 3)
print("\n--- Reshape menjadi (4, 3) ---")
print(matriks_4x3)
print("Bentuk baru:", matriks_4x3.shape)

print("\n--- Mencoba Reshape menjadi (3, 3) ---")
try:
    matriks_gagal = vektor_panjang.reshape(3, 3)
except ValueError as e:
    print(f"ERROR: {e}")
    print("-> Gagal! Karena 3 * 3 = 9, bukan 12. Jumlah elemen harus tetap sama.")

--- Array Asli (1D, 2D elemen) ---
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Bentuk asli: (12,)
Ukuran asli: 12

--- Reshape menjadi (3, 4) ---
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Bentuk baru: (3, 4)

--- Reshape menjadi (4, 3) ---
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Bentuk baru: (4, 3)

--- Mencoba Reshape menjadi (3, 3) ---
ERROR: cannot reshape array of size 12 into shape (3,3)
-> Gagal! Karena 3 * 3 = 9, bukan 12. Jumlah elemen harus tetap sama.


In [4]:
matriks_asli = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print("--- Matriks Asli ---")
print(matriks_asli)
print("Bentuk asli:", matriks_asli.shape)

matriks_transpose = matriks_asli.T

print("\n--- Matriks Setelah di-Transpose ---")
print(matriks_transpose)
print("Bentuk baru:", matriks_transpose.shape)

--- Matriks Asli ---
[[1 2]
 [3 4]
 [5 6]]
Bentuk asli: (3, 2)

--- Matriks Setelah di-Transpose ---
[[1 3 5]
 [2 4 6]]
Bentuk baru: (2, 3)


In [7]:
data_pagi = np.array([[1, 2, 3], [4, 5, 6]])
data_sore = np.array([[7, 8, 9], [10, 11, 12]])

print("--- Data Pagi (bentuk 2x3) ---")
print(data_pagi)
print("\n--- Data Sore (bentuk 2x3) ---")
print(data_sore)

print("\n" + "="*50 + "\n")
data_harian_v = np.vstack((data_pagi, data_sore))

print("Hasil vstack (ditumpuk secara vertikal):")
print(data_harian_v)
print("Bentuk baru:", data_harian_v.shape)

print("\n" + "="*50 + "\n")
data_harian_h = np.hstack((data_pagi, data_sore))

print("Hasil hstack (ditumpuk secara horizontal):")
print(data_harian_h)
print("Bentuk baru:", data_harian_h.shape)

--- Data Pagi (bentuk 2x3) ---
[[1 2 3]
 [4 5 6]]

--- Data Sore (bentuk 2x3) ---
[[ 7  8  9]
 [10 11 12]]


Hasil vstack (ditumpuk secara vertikal):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Bentuk baru: (4, 3)


Hasil hstack (ditumpuk secara horizontal):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Bentuk baru: (2, 6)
