In [1]:
import numpy as np

# Sumber 1: Data nilai mentah dari sistem input dosen
data_nilai_mentah = [
    {'nama': 'Nanda', 'nilai': [85, 90, 78, 92]},
    {'nama': 'Changli', 'nilai': [95, 88, 92, 97]},
    {'nama': 'Maisie', 'nilai': [70, 75, 80, 72]},
    {'nama': 'Vedal', 'nilai': [60, 65, 70, 68]},
    {'nama': 'Neuro-sama', 'nilai': [100, 50, 75, 85]} # Nilainya tidak stabil
]

# Sumber 2: Bobot dari kurikulum
# [Bobot Graf, Bobot Basis Data, Bobot Algoritma, Bobot RPL]
bobot_matkul = np.array([0.3, 0.3, 0.2, 0.2])

# Sumber 3: Data kehadiran dari sistem absensi
data_kehadiran = {
    'Nanda': 0.95,      # Kehadiran 95%
    'Changli': 0.98,
    'Maisie': 0.85,
    'Vedal': 0.92,
    'Neuro-sama': 0.70
}

In [2]:
def proses_data(data_mentah):
    daftar_nama = []
    list_nilai_mentah = []
    for mahasiswa in data_mentah:
        daftar_nama.append(mahasiswa['nama'])
        list_nilai_mentah.append(mahasiswa['nilai'])
    matriks_nilai = np.array([list_nilai_mentah])
    return daftar_nama, matriks_nilai.reshape(5, 4)
daftar_nama, matriks_nilai = proses_data(data_nilai_mentah)
print(daftar_nama)
print(matriks_nilai)

['Nanda', 'Changli', 'Maisie', 'Vedal', 'Neuro-sama']
[[ 85  90  78  92]
 [ 95  88  92  97]
 [ 70  75  80  72]
 [ 60  65  70  68]
 [100  50  75  85]]


In [3]:
skor_akhir_tertimbang = matriks_nilai @ bobot_matkul.reshape(-1, 1)
print(skor_akhir_tertimbang)

[[86.5]
 [92.7]
 [73.9]
 [65.1]
 [77. ]]


In [9]:
list_kehadiran = [data_kehadiran[nama] for nama in daftar_nama]
array_kehadiran = np.array(list_kehadiran)
print(array_kehadiran, "\n")
mask_bonus = array_kehadiran > 0.90 #Bagaimana kalau 0.9?
print(mask_bonus, "\n")
skor_final_dengan_bonus = skor_akhir_tertimbang.copy().reshape(5, 1)
skor_final_dengan_bonus[mask_bonus] += 3 #Harus pakai .reshape disini
print(skor_akhir_tertimbang, "\n")
print(skor_final_dengan_bonus)

[0.95 0.98 0.85 0.92 0.7 ] 

[ True  True False  True False] 

[[86.5]
 [92.7]
 [73.9]
 [65.1]
 [77. ]] 

[[89.5]
 [95.7]
 [73.9]
 [68.1]
 [77. ]]
(5, 1)


In [5]:
for i in range(len(daftar_nama)):
    print(f"Nama Mahasiswa: {daftar_nama[i]}")
    print(f"Daftar Nilai Mahasiswa: \n{matriks_nilai[i ,:]}")
    print(f"Skor Akhir: {skor_final_dengan_bonus[i]}\n")

Nama Mahasiswa: Nanda
Daftar Nilai Mahasiswa: 
[85 90 78 92]
Skor Akhir: [89.5]

Nama Mahasiswa: Changli
Daftar Nilai Mahasiswa: 
[95 88 92 97]
Skor Akhir: [95.7]

Nama Mahasiswa: Maisie
Daftar Nilai Mahasiswa: 
[70 75 80 72]
Skor Akhir: [73.9]

Nama Mahasiswa: Vedal
Daftar Nilai Mahasiswa: 
[60 65 70 68]
Skor Akhir: [68.1]

Nama Mahasiswa: Neuro-sama
Daftar Nilai Mahasiswa: 
[100  50  75  85]
Skor Akhir: [77.]



In [6]:
array_daftar_nama = np.array(daftar_nama)
indeks_peringkat = np.argsort(-skor_final_dengan_bonus.flatten())
nama_terurut = array_daftar_nama[indeks_peringkat]
skor_terurut = skor_final_dengan_bonus[indeks_peringkat]
print("--- Papan Peringkat Final ---")
for i in range(len(nama_terurut)):
    print(f"Peringkat {i+1}: {nama_terurut[i]} - Skor: {skor_terurut[i][0]:.1f}")

--- Papan Peringkat Final ---
Peringkat 1: Changli - Skor: 95.7
Peringkat 2: Nanda - Skor: 89.5
Peringkat 3: Neuro-sama - Skor: 77.0
Peringkat 4: Maisie - Skor: 73.9
Peringkat 5: Vedal - Skor: 68.1


In [12]:
rerata_nilai_matkul = matriks_nilai.mean(axis=1)
deviasi_skor = matriks_nilai - rerata_nilai_matkul.reshape(5, 1)
print(f"Deviasi Skor: \n{deviasi_skor}")

laporan_numerik_final = np.hstack((matriks_nilai, skor_final_dengan_bonus))
header_laporan = "Nilai_Graf, Nilai_BasisData, Nilai_Algoritma, Nilai_RPL, Skor_Final"
np.savetxt("laporan_akademik(day-21).csv",
          laporan_numerik_final,
          delimiter=",",
          fmt="%.2f",
          header=header_laporan,
          comments="")
print("\nLaporan telah berhasil diekspor ke file 'lapran_akademik(day-21).csv'")
print("Silakan cek folder di mana notebook ini berada!")

Deviasi Skor: 
[[ -1.25   3.75  -8.25   5.75]
 [  2.    -5.    -1.     4.  ]
 [ -4.25   0.75   5.75  -2.25]
 [ -5.75  -0.75   4.25   2.25]
 [ 22.5  -27.5   -2.5    7.5 ]]

Laporan telah berhasil diekspor ke file 'lapran_akademik(day-21).csv'
Silakan cek folder di mana notebook ini berada!
