In [1]:
import numpy as np

In [2]:
stok_awal = np.array([
    [10, 15, 25],
    [20, 30, 12]
])

stok_masuk = np.array([
    [5, 10, 5],
    [8, 5, 15]
])

stok_akhir = stok_awal + stok_masuk

print("--- Stok Awal ---")
print(stok_awal)
print("\n--- Stok Masuk ---")
print(stok_masuk)
print("\n--- Stok Akhir (Hasil Penjumlahan) ---")
print(stok_akhir)

--- Stok Awal ---
[[10 15 25]
 [20 30 12]]

--- Stok Masuk ---
[[ 5 10  5]
 [ 8  5 15]]

--- Stok Akhir (Hasil Penjumlahan) ---
[[15 25 30]
 [28 35 27]]


In [3]:
stok_setelah_biaya = stok_akhir - 2

print("--- Stok Akhir ---")
print(stok_akhir)
print("\n--- Stok Setelah Biaya (Hasil Broadcasting) ---")
print(stok_setelah_biaya)

--- Stok Akhir ---
[[15 25 30]
 [28 35 27]]

--- Stok Setelah Biaya (Hasil Broadcasting) ---
[[13 23 28]
 [26 33 25]]


In [4]:
data_pertarungan = np.array([
    [1500, 200, 60],
    [2200, 150, 90],
    [1800, 300, 75],
    [3000, 100, 120],
    [1200, 400, 80]
])
bonus_buff = np.array([100, -50, 10])
data_setelah_buff = data_pertarungan + bonus_buff

print("--- Data Pertarungan Awal ---")
print(data_pertarungan)
print("\n--- Bonus Buff (1 Baris) ---")
print(bonus_buff)
print("\n--- Data Setelah Buff (Hasil Broadcasting) ---")
print(data_setelah_buff)

--- Data Pertarungan Awal ---
[[1500  200   60]
 [2200  150   90]
 [1800  300   75]
 [3000  100  120]
 [1200  400   80]]

--- Bonus Buff (1 Baris) ---
[100 -50  10]

--- Data Setelah Buff (Hasil Broadcasting) ---
[[1600  150   70]
 [2300  100  100]
 [1900  250   85]
 [3100   50  130]
 [1300  350   90]]


In [6]:
# Menghasilkan data untuk 10 pertarungan, 5 metrik
# Metrik: [damage_dealt, damage_taken, healing_done, assists, duration]
data_harian = np.random.randint(low=500, high=5000, size=(10, 5))
debuff_fatigue = np.random.randint(low=50, high=200, size=(10, 5))
data_setelah_lelah = data_harian - debuff_fatigue
buff_server = np.array([500, -100, 200, 20, 10])
data_final = data_setelah_lelah + buff_server

print("--- Data Pertarungan Harian (10x5) ---")
print(data_harian)
print("\n--- Data Pertarungan Setelah Lelah ---")
print(data_setelah_lelah)
print("\n--- Data Final Setelah Menerima Server Buff ---")
print(data_final)

--- Data Pertarungan Harian (10x5) ---
[[2971 3502 1239 2588 3030]
 [4119 1489 4566 1438 3357]
 [2520 4907 4955 3625 1547]
 [4708 4021 3921 3702  755]
 [2315 2242 3463 3649 3873]
 [ 956 1225 3987 1649 4596]
 [4108 2518 2742 3583 1328]
 [2912 2590  712 4993 4643]
 [3094 3106 1693 1742  992]
 [1359 2551 4440 4205 4436]]

--- Data Pertarungan Setelah Lelah ---
[[2884 3355 1044 2524 2936]
 [3968 1414 4412 1303 3215]
 [2346 4708 4877 3514 1457]
 [4547 3880 3855 3580  691]
 [2238 2143 3389 3563 3690]
 [ 802 1101 3874 1539 4539]
 [4052 2424 2600 3515 1241]
 [2778 2493  536 4893 4558]
 [2995 3046 1625 1592  901]
 [1265 2424 4261 4127 4267]]

--- Data Final Setelah Menerima Server Buff ---
[[3384 3255 1244 2544 2946]
 [4468 1314 4612 1323 3225]
 [2846 4608 5077 3534 1467]
 [5047 3780 4055 3600  701]
 [2738 2043 3589 3583 3700]
 [1302 1001 4074 1559 4549]
 [4552 2324 2800 3535 1251]
 [3278 2393  736 4913 4568]
 [3495 2946 1825 1612  911]
 [1765 2324 4461 4147 4277]]
